Fixes for native command success/failure & supporting multiple Vault names within KeyChain
SteveL-MSFT/SecretManagement.KeyChain pull request #3
Opened 2020-11-11 02:04 UTC by DonPwrShellHunt

This addresses issue #1 and accommodates multiple VaultName objects handled by the KeyChain extension.

2020-11-12 21:29 UTC, SteveL-MSFT requested changes
Overall, the changes look good!  Thanks!  One feedback that needs to be addressed before I can merge and publish a new version.

2020-11-12 21:29 UTC, SteveL-MSFT commented on src/SecretManagement.KeyChain/SecretManagement.KeyChain.psd1
> +    RequiredModules = @('Microsoft.PowerShell.SecretManagement')
This is deliberately commented out for now as PowerShellGet has a problem with resolving dependencies on preview modules.  Need to keep this commented out until SecretManagement is no longer a prerelease.

2020-11-12 22:42 UTC, DonPwrShellHunt commented
Commented out RequiredModules in psd1 as requested.

2020-11-12 23:12 UTC, SteveL-MSFT approved these changes

2020-11-12 23:12 UTC, merged

2020-11-20 18:34 UTC, SteveL-MSFT commented
@DonPwrShellHunt sorry for the delay as I was busy with some other things, but published this update right now https://www.powershellgallery.com/packages/SecretManagement.KeyChain/0.1.2