fix-keychain-create
SteveL-MSFT/SecretManagement.KeyChain pull request #6
Opened 2021-02-25 18:43 UTC by DonPwrShellHunt

Fix logic in Test-SecretVault that detects keychain needs to be created. Added verbose output to this cmdlet & README content to describe first use of extension.

2021-02-25 20:31 UTC, DonPwrShellHunt commented
This pull request should resolve issue #5

2021-03-01 23:35 UTC, SteveL-MSFT requested changes

2021-03-01 23:35 UTC, SteveL-MSFT commented on README.md
> +```powershell
Should make this ` ```console` instead since it's also showing the output, then use `PS>` to show where the prompts are vs the output

2021-03-01 23:35 UTC, SteveL-MSFT commented on README.md
> +Get-KeyChainConfiguration (new keychain will be created in this step)
I prefer to show comments as comments:

```console
# new keychain will be created in this step
PS> Get-KeyChainConfiguration
```

2021-03-02 04:48 UTC, SteveL-MSFT approved these changes

2021-03-02 04:48 UTC, merged